// lib/dispensation.js
// Article 31: the one mechanism in this repository that deliberately
// bypasses the ordinary graduated procession of Article 6. Proclus's own
// cosmos has no analogue for this — it is added knowingly. Every
// invocation is logged as an explicit exception and MUST generate a
// mandatory retroactive correction-proposal before it can be closed.
// The trigger conditions themselves are Intellect-grade (Article 30) and
// are never redefined here.

const db = require('./db');
const { getParam } = require('./parameters');
const { recordReversionEvent } = require('./reversion');
const { createProposal } = require('./proposals');

function getTriggerConditions() {
    return getParam('dispensation_trigger_conditions', []);
}

/**
 * Invoke a dispensation. `triggeringConditionKey` must match one of the
 * keys currently defined in the Intellect-grade dispensation_trigger_conditions
 * parameter (Article 30) — Psyche does not get to invent a new condition
 * on the spot.
 */
function invokeDispensation({ triggeringConditionKey, actionTaken, contradictedIntellectVersionId = null }) {
    const conditions = getTriggerConditions();
    const matched = conditions.find(c => c.key === triggeringConditionKey);
    if (!matched) {
        throw new Error(
            `Article 30: "${triggeringConditionKey}" is not a currently defined dispensation trigger condition. ` +
            `Psyche may invoke a dispensation but may never redefine what qualifies for one.`
        );
    }

    // Article 31: the retroactive correction-proposal is mandatory and is
    // created in the same transaction as the dispensation record, never as
    // an optional follow-up step.
    const tx = db.transaction(() => {
        const proposalId = createProposal({
            proposalType: 'correction',
            content: `Retroactive review required: Psyche invoked Dispensation under condition "${triggeringConditionKey}". Action taken: ${actionTaken}`,
            contestedIntellectVersionId: contradictedIntellectVersionId,
            evidence: `Automatically generated by Article 31 dispensation. Requires Architect review before this dispensation record may be closed.`
        });

        const dispensationId = db.prepare(`
            INSERT INTO dispensation_records
                (triggering_condition, action_taken, contradicted_intellect_version_id, retroactive_proposal_id, status)
            VALUES (?, ?, ?, ?, 'open')
        `).run(triggeringConditionKey, actionTaken, contradictedIntellectVersionId, proposalId).lastInsertRowid;

        recordReversionEvent({
            sourceGrade: 'psyche',
            targetGrade: 'intellect',
            eventType: 'dispensation',
            causeType: 'final',
            outcome: 'noted',
            correctionNote: `Dispensation #${dispensationId} invoked; mandatory retroactive proposal #${proposalId} created.`
        });

        return dispensationId;
    });

    return tx();
}

function closeDispensation(dispensationId, { architectConfirmed }) {
    if (!architectConfirmed) {
        throw new Error('Article 31: closing a dispensation requires explicit Architect review.');
    }
    const record = db.prepare(`SELECT * FROM dispensation_records WHERE id = ?`).get(dispensationId);
    if (!record) throw new Error('Dispensation record not found');
    if (!record.retroactive_proposal_id) {
        throw new Error('Article 31: cannot close a dispensation with no retroactive proposal on file.');
    }
    const proposal = db.prepare(`SELECT * FROM proposals WHERE id = ?`).get(record.retroactive_proposal_id);
    if (!proposal || proposal.status === 'open') {
        throw new Error('Article 31: the retroactive proposal must be resolved before the dispensation can be closed.');
    }
    db.prepare(`UPDATE dispensation_records SET status = 'closed', closed_at = datetime('now') WHERE id = ?`).run(dispensationId);
}

module.exports = { getTriggerConditions, invokeDispensation, closeDispensation };
